export const SOURCE_REGISTRY = [
  {
    name: "CISA Advisories",
    publisher: "CISA",
    type: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_type: "government_advisory",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Microsoft Security Blog",
    publisher: "Microsoft",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    source_type: "threat_intel",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Cloud Threat Intelligence",
    publisher: "Google Cloud / Mandiant",
    type: "rss",
    url: "https://cloud.google.com/blog/topics/threat-intelligence/rss/",
    source_type: "threat_intel",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Security Blog",
    publisher: "Google",
    type: "atom",
    url: "https://security.googleblog.com/feeds/posts/default",
    source_type: "security_blog",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "OWASP",
    publisher: "OWASP",
    type: "rss",
    url: "https://owasp.org/feed.xml",
    source_type: "security_framework",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "CSA Singapore",
    publisher: "Cyber Security Agency of Singapore",
    type: "rss",
    url: "https://www.csa.gov.sg/rss",
    source_type: "government_advisory",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: false,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "html_reference",
    url: "https://www.nist.gov/artificial-intelligence",
    source_type: "policy_update",
    trust_tier: "primary",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "OECD AI",
    publisher: "OECD AI Policy Observatory",
    type: "html_reference",
    url: "https://oecd.ai/",
    source_type: "policy_update",
    trust_tier: "high",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
  name: "The Hacker News",
  publisher: "The Hacker News",
  type: "rss",
  url: "https://feeds.feedburner.com/TheHackersNews?format=xml",
  source_type: "security_blog",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Dark Reading",
  publisher: "Dark Reading",
  type: "rss",
  url: "https://www.darkreading.com/rss.xml",
  source_type: "security_blog",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Krebs on Security",
  publisher: "Krebs on Security",
  type: "rss",
  url: "https://krebsonsecurity.com/feed/",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "SANS Internet Storm Center",
  publisher: "SANS ISC",
  type: "rss",
  url: "https://isc.sans.edu/rssfeed_full.xml",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},

// ── AI incident tracking ──────────────────────────────────────────────────────

{
  // AI Incident Database — real-world harms and failures from AI systems
  name: "AI Incident Database",
  publisher: "AI Incident Database",
  type: "rss",
  url: "https://incidentdatabase.ai/rss.xml",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "official_rss",
  enabled: true,
},
{
  // AVID — AI Vulnerability Database (blog/research on AI failure modes)
  name: "AVID AI Vulnerability Blog",
  publisher: "AVID (AI Vulnerability Database)",
  type: "rss",
  url: "https://avidml.org/blog/index.xml",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // ML Safety Newsletter — tracks AI safety incidents, research, and policy signals
  name: "ML Safety Newsletter",
  publisher: "Center for AI Safety",
  type: "rss",
  url: "https://newsletter.mlsafety.org/feed",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},

// ── Horizon scanning: AI policy, strategy and foresight ──────────────────────

{
  // Georgetown CSET — AI policy, security, geopolitics. Excellent horizon signal.
  name: "Georgetown CSET",
  publisher: "Georgetown CSET",
  type: "rss",
  url: "https://cset.georgetown.edu/feed/",
  source_type: "policy_update",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // MIT Technology Review — AI/technology implications for security and society
  name: "MIT Technology Review AI",
  publisher: "MIT Technology Review",
  type: "rss",
  url: "https://www.technologyreview.com/feed/",
  source_type: "news",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // The Register security — often breaks enterprise AI security stories early
  name: "The Register Security",
  publisher: "The Register",
  type: "atom",
  url: "https://www.theregister.com/security/headlines.atom",
  source_type: "news",
  trust_tier: "medium",
  retrieval_method: "official_atom",
  enabled: true,
},

// ── Adversarial ML & AI red teaming ──────────────────────────────────────────

{
  // Adversa AI — adversarial ML, AI red teaming, model attack research
  name: "Adversa AI Research",
  publisher: "Adversa AI",
  type: "rss",
  url: "https://adversa.ai/blog/feed/",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // HiddenLayer — ML model security, supply chain, detection evasion
  name: "HiddenLayer Research",
  publisher: "HiddenLayer",
  type: "rss",
  url: "https://hiddenlayer.com/research/feed/",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // Protect AI — AI/ML security, model scanning, MLOps threats
  name: "Protect AI Blog",
  publisher: "Protect AI",
  type: "rss",
  url: "https://protectai.com/blog/rss.xml",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // Lakera AI — LLM security, prompt injection, guardrail research
  name: "Lakera AI Blog",
  publisher: "Lakera AI",
  type: "rss",
  url: "https://www.lakera.ai/blog/feed",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // Bishop Fox — offensive security research including AI attack techniques
  name: "Bishop Fox Blog",
  publisher: "Bishop Fox",
  type: "rss",
  url: "https://bishopfox.com/blog/feed",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},

// ── AI-specific security research and incident feeds ─────────────────────────

{
  // Prompt injection, agentic AI attacks, LLM security research
  name: "Embrace The Red",
  publisher: "Wunderwuzzi (Embrace The Red)",
  type: "rss",
  url: "https://embracethered.com/blog/rss.xml",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // AI security practitioner analysis — Simon Willison
  name: "Simon Willison's Weblog",
  publisher: "Simon Willison",
  type: "atom",
  url: "https://simonwillison.net/atom/everything/",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "official_atom",
  enabled: true,
},
{
  // Trail of Bits — security research including AI/ML
  name: "Trail of Bits Blog",
  publisher: "Trail of Bits",
  type: "rss",
  url: "https://blog.trailofbits.com/index.xml",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // Elastic Security Labs — threat research, AI attack technique coverage
  name: "Elastic Security Labs",
  publisher: "Elastic",
  type: "rss",
  url: "https://www.elastic.co/security-labs/rss/feed.xml",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  // Anthropic security / safety research updates
  name: "Anthropic News",
  publisher: "Anthropic",
  type: "atom",
  url: "https://www.anthropic.com/rss.xml",
  source_type: "ai_lab_update",
  trust_tier: "primary",
  retrieval_method: "official_atom",
  enabled: true,
},
{
  // OpenAI safety and research blog
  name: "OpenAI Blog",
  publisher: "OpenAI",
  type: "rss",
  url: "https://openai.com/blog/rss.xml",
  source_type: "ai_lab_update",
  trust_tier: "primary",
  retrieval_method: "official_rss",
  enabled: true,
},
{
  // NIST AI Risk Management, AI safety standards
  name: "NIST AI",
  publisher: "NIST",
  type: "rss",
  url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
  source_type: "policy_update",
  trust_tier: "primary",
  retrieval_method: "official_rss",
  enabled: true,
},

// ── AI-focused threat intelligence ───────────────────────────────────────────

{
  name: "Unit 42 Threat Research",
  publisher: "Palo Alto Networks Unit 42",
  type: "rss",
  url: "https://unit42.paloaltonetworks.com/feed/",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "CrowdStrike Blog",
  publisher: "CrowdStrike",
  type: "rss",
  url: "https://www.crowdstrike.com/blog/feed/",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Recorded Future Blog",
  publisher: "Recorded Future",
  type: "rss",
  url: "https://www.recordedfuture.com/feed",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "IBM Security Intelligence",
  publisher: "IBM Security",
  type: "rss",
  url: "https://securityintelligence.com/feed/",
  source_type: "threat_intel",
  trust_tier: "high",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Schneier on Security",
  publisher: "Bruce Schneier",
  type: "atom",
  url: "https://www.schneier.com/feed/atom/",
  source_type: "security_blog",
  trust_tier: "high",
  retrieval_method: "official_atom",
  enabled: true,
},

// ── Government and regulatory (AI/cyber policy) ───────────────────────────────

{
  name: "NCSC UK",
  publisher: "UK National Cyber Security Centre",
  type: "atom",
  url: "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml",
  source_type: "government_advisory",
  trust_tier: "primary",
  retrieval_method: "official_atom",
  enabled: true,
},
{
  name: "CSA Singapore",
  publisher: "Cyber Security Agency of Singapore",
  type: "rss",
  url: "https://www.csa.gov.sg/rss",
  source_type: "government_advisory",
  trust_tier: "primary",
  retrieval_method: "official_rss",
  enabled: true,
},
{
  name: "ENISA News",
  publisher: "European Union Agency for Cybersecurity",
  type: "rss",
  url: "https://www.enisa.europa.eu/news/rss",
  source_type: "government_advisory",
  trust_tier: "primary",
  retrieval_method: "official_rss",
  enabled: true,
},

// ── Broad security news (high volume, AI content filtered at classify time) ───

{
  name: "BleepingComputer",
  publisher: "BleepingComputer",
  type: "rss",
  url: "https://www.bleepingcomputer.com/feed/",
  source_type: "security_blog",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "SecurityWeek",
  publisher: "SecurityWeek",
  type: "rss",
  url: "https://feeds.feedburner.com/Securityweek",
  source_type: "security_blog",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Help Net Security",
  publisher: "Help Net Security",
  type: "rss",
  url: "https://www.helpnetsecurity.com/feed/",
  source_type: "security_blog",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Ars Technica Security",
  publisher: "Ars Technica",
  type: "rss",
  url: "https://feeds.arstechnica.com/arstechnica/security",
  source_type: "news",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
{
  name: "Wired Security",
  publisher: "Wired",
  type: "rss",
  url: "https://www.wired.com/feed/tag/security/latest/rss",
  source_type: "news",
  trust_tier: "medium",
  retrieval_method: "rss",
  enabled: true,
},
];
