export const SOURCE_REGISTRY = [
  {
    name: "CISA Advisories",
    publisher: "CISA",
    type: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_type: "government_advisory",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Microsoft Security Blog",
    publisher: "Microsoft",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    source_type: "threat_intel",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Cloud Threat Intelligence",
    publisher: "Google Cloud / Mandiant",
    type: "rss",
    url: "https://cloud.google.com/blog/topics/threat-intelligence/rss/",
    source_type: "threat_intel",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Security Blog",
    publisher: "Google",
    type: "atom",
    url: "https://security.googleblog.com/feeds/posts/default",
    source_type: "security_blog",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "OWASP",
    publisher: "OWASP",
    type: "rss",
    url: "https://owasp.org/feed.xml",
    source_type: "security_framework",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "CSA Singapore",
    publisher: "Cyber Security Agency of Singapore",
    type: "rss",
    url: "https://www.csa.gov.sg/rss",
    source_type: "government_advisory",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: false,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "html_reference",
    url: "https://www.nist.gov/artificial-intelligence",
    source_type: "policy_update",
    trust_tier: "primary",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "OECD AI",
    publisher: "OECD AI Policy Observatory",
    type: "html_reference",
    url: "https://oecd.ai/",
    source_type: "policy_update",
    trust_tier: "high",
    retrieval_method: "official_site",
    enabled: false,
  },
];
