/**
 * Source registry — connector definitions for ingestion.
 *
 * source_type values MUST be from the controlled vocabulary in
 * lib/config/sourceTypes.js. Layer 5 (validateAndTypeSource) will
 * re-classify any source whose source_type doesn't match, but setting
 * the right value here avoids redundant work.
 *
 * Acceptable source_type values:
 *   vulnerability, incident, exploit_disclosure, research_finding,
 *   threat_intelligence, defensive_capability, benchmark_evaluation,
 *   governance_signal, ecosystem_signal, societal_harm_signal,
 *   capability_demonstration, adversary_adoption_signal,
 *   infrastructure_dependency_signal, trust_boundary_shift,
 *   strategic_signal, unknown
 */

export const SOURCE_REGISTRY = [
  {
    name: "CISA Advisories",
    publisher: "CISA",
    type: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Microsoft Security Blog",
    publisher: "Microsoft",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Cloud Threat Intelligence",
    publisher: "Google Cloud / Mandiant",
    type: "rss",
    url: "https://cloud.google.com/blog/topics/threat-intelligence/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Security Blog",
    publisher: "Google",
    type: "atom",
    url: "https://security.googleblog.com/feeds/posts/default",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "OWASP",
    publisher: "OWASP",
    type: "rss",
    url: "https://owasp.org/feed.xml",
    source_type: "defensive_capability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "html_reference",
    url: "https://www.nist.gov/artificial-intelligence",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "OECD AI",
    publisher: "OECD AI Policy Observatory",
    type: "html_reference",
    url: "https://oecd.ai/",
    source_type: "governance_signal",
    trust_tier: "high",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "The Hacker News",
    publisher: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews?format=xml",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Dark Reading",
    publisher: "Dark Reading",
    type: "rss",
    url: "https://www.darkreading.com/rss.xml",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Krebs on Security",
    publisher: "Krebs on Security",
    type: "rss",
    url: "https://krebsonsecurity.com/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "SANS Internet Storm Center",
    publisher: "SANS ISC",
    type: "rss",
    url: "https://isc.sans.edu/rssfeed_full.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI incident tracking ──────────────────────────────────────────────────────

  {
    name: "AI Incident Database",
    publisher: "AI Incident Database",
    type: "rss",
    url: "https://incidentdatabase.ai/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "AVID AI Vulnerability Blog",
    publisher: "AVID (AI Vulnerability Database)",
    type: "rss",
    url: "https://avidml.org/blog/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "ML Safety Newsletter",
    publisher: "Center for AI Safety",
    type: "rss",
    url: "https://newsletter.mlsafety.org/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── Horizon scanning: AI policy, strategy and foresight ──────────────────────

  {
    name: "Georgetown CSET",
    publisher: "Georgetown CSET",
    type: "rss",
    url: "https://cset.georgetown.edu/feed/",
    source_type: "governance_signal",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "MIT Technology Review AI",
    publisher: "MIT Technology Review",
    type: "rss",
    url: "https://www.technologyreview.com/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "The Register Security",
    publisher: "The Register",
    type: "atom",
    url: "https://www.theregister.com/security/headlines.atom",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "official_atom",
    enabled: true,
  },

  // ── Adversarial ML & AI red teaming ──────────────────────────────────────────

  {
    name: "Adversa AI Research",
    publisher: "Adversa AI",
    type: "rss",
    url: "https://adversa.ai/blog/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "HiddenLayer Research",
    publisher: "HiddenLayer",
    type: "rss",
    url: "https://hiddenlayer.com/research/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Protect AI Blog",
    publisher: "Protect AI",
    type: "rss",
    url: "https://protectai.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Lakera AI Blog",
    publisher: "Lakera AI",
    type: "rss",
    url: "https://www.lakera.ai/blog/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Bishop Fox Blog",
    publisher: "Bishop Fox",
    type: "rss",
    url: "https://bishopfox.com/blog/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI-specific security research and incident feeds ─────────────────────────

  {
    name: "Embrace The Red",
    publisher: "Wunderwuzzi (Embrace The Red)",
    type: "rss",
    url: "https://embracethered.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Simon Willison's Weblog",
    publisher: "Simon Willison",
    type: "atom",
    url: "https://simonwillison.net/atom/everything/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "Trail of Bits Blog",
    publisher: "Trail of Bits",
    type: "rss",
    url: "https://blog.trailofbits.com/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Elastic Security Labs",
    publisher: "Elastic",
    type: "rss",
    url: "https://www.elastic.co/security-labs/rss/feed.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Anthropic News",
    publisher: "Anthropic",
    type: "atom",
    url: "https://www.anthropic.com/rss.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "OpenAI Blog",
    publisher: "OpenAI",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "rss",
    url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── AI-focused threat intelligence ───────────────────────────────────────────

  {
    name: "Unit 42 Threat Research",
    publisher: "Palo Alto Networks Unit 42",
    type: "rss",
    url: "https://unit42.paloaltonetworks.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "CrowdStrike Blog",
    publisher: "CrowdStrike",
    type: "rss",
    url: "https://www.crowdstrike.com/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Recorded Future Blog",
    publisher: "Recorded Future",
    type: "rss",
    url: "https://www.recordedfuture.com/feed",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "IBM Security Intelligence",
    publisher: "IBM Security",
    type: "rss",
    url: "https://securityintelligence.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Schneier on Security",
    publisher: "Bruce Schneier",
    type: "atom",
    url: "https://www.schneier.com/feed/atom/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },

  // ── Government and regulatory (AI/cyber policy) ───────────────────────────────

  {
    name: "NCSC UK",
    publisher: "UK National Cyber Security Centre",
    type: "atom",
    url: "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "CSA Singapore",
    publisher: "Cyber Security Agency of Singapore",
    type: "rss",
    url: "https://www.csa.gov.sg/rss",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "ENISA News",
    publisher: "European Union Agency for Cybersecurity",
    type: "rss",
    url: "https://www.enisa.europa.eu/news/rss",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Broad security news (high volume, AI content filtered at classify time) ───

  {
    name: "BleepingComputer",
    publisher: "BleepingComputer",
    type: "rss",
    url: "https://www.bleepingcomputer.com/feed/",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "SecurityWeek",
    publisher: "SecurityWeek",
    type: "rss",
    url: "https://feeds.feedburner.com/Securityweek",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Help Net Security",
    publisher: "Help Net Security",
    type: "rss",
    url: "https://www.helpnetsecurity.com/feed/",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Ars Technica Security",
    publisher: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/security",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Wired Security",
    publisher: "Wired",
    type: "rss",
    url: "https://www.wired.com/feed/tag/security/latest/rss",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
];
