/**
 * v2 — buildCorpusSummary()
 *
 * Replaces the 11-step analytics branch (14 files, ~200K LOC including
 * analyticsAggregation 47K, visualizationSpecs 52K) with simple counting
 * over the understood sources. No LLM. No pre-computed chart specs.
 *
 * The output is used:
 *   1. As context for the synthesis LLM (prevents overconfident claims on thin evidence)
 *   2. As the data layer for dashboard widgets
 *   3. For the evidence graph (nodes + edges)
 *
 * Visualisation specs are generated by the dashboard on demand, not pre-computed.
 */

import { PRIMARY_TAGS } from "./taxonomy.js";

// ── Domain colours (for dashboard charts) ─────────────────────────────────────

export const DOMAIN_COLOURS = {
  traditional_ai_threats: "#6366f1",
  llm_threats:            "#f59e0b",
  agentic_ai_threats:     "#10b981",
  ai_enabled_threats:     "#ef4444",
  unclear_or_adjacent:    "#94a3b8",
};

// ── Main aggregation ──────────────────────────────────────────────────────────

/**
 * Build a corpus summary from understood sources.
 *
 * @param {object[]} sources     - Output of understandAllSources().relevant
 * @param {object[]} allSources  - Full source list (including discarded)
 * @returns {object}             Corpus summary
 */
export function buildCorpusSummary(sources, allSources = []) {
  const total_sources     = allSources.length;
  const relevant_sources  = sources.length;

  // Category counts
  const source_count_by_category = {};
  for (const s of sources) {
    const cat = s.category || "unclear_or_adjacent";
    source_count_by_category[cat] = (source_count_by_category[cat] || 0) + 1;
  }

  // Source type counts
  const source_count_by_type = {};
  for (const s of sources) {
    const t = s.source_type || "unknown";
    source_count_by_type[t] = (source_count_by_type[t] || 0) + 1;
  }

  // Trust tier breakdown per category
  const trust_by_category = {};
  for (const s of sources) {
    const cat = s.category || "unclear_or_adjacent";
    if (!trust_by_category[cat]) trust_by_category[cat] = {};
    const tier = s.trust_tier || "unknown";
    trust_by_category[cat][tier] = (trust_by_category[cat][tier] || 0) + 1;
  }

  // Date range
  const dates = sources
    .map(s => s.date_published)
    .filter(d => d && d.length >= 7)
    .sort();
  const date_range = dates.length >= 2
    ? `${dates[0].slice(0, 10)} to ${dates[dates.length - 1].slice(0, 10)}`
    : dates[0]?.slice(0, 10) || "unknown";

  // Tag frequency (for trend detection)
  const tag_frequency = {};
  for (const s of sources) {
    for (const tag of s.primary_tags || []) {
      tag_frequency[tag] = (tag_frequency[tag] || 0) + 1;
    }
  }

  // Top entities across corpus
  const entity_freq = {};
  for (const s of sources) {
    for (const e of s.key_entities || []) {
      entity_freq[e] = (entity_freq[e] || 0) + 1;
    }
  }
  const top_entities = Object.entries(entity_freq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([entity, count]) => ({ entity, count }));

  // Per-category summaries (for synthesis context string)
  const category_coverage_notes = Object.entries(source_count_by_category).map(([cat, n]) => {
    const tiers = trust_by_category[cat] || {};
    const highTrustCount = (tiers.primary || 0) + (tiers.high || 0);
    const note = highTrustCount > 0
      ? `${n} sources (${highTrustCount} high-trust)`
      : `${n} sources (no high-trust sources — confidence ceiling: medium)`;
    return `  ${cat}: ${note}`;
  });

  // Thin category warning
  const thin_categories = Object.entries(source_count_by_category)
    .filter(([, n]) => n < 3)
    .map(([cat]) => cat);

  return {
    total_sources,
    relevant_sources,
    discarded_sources: total_sources - relevant_sources,
    date_range,
    source_count_by_category,
    source_count_by_type,
    trust_by_category,
    tag_frequency,
    top_entities,
    thin_categories,
    category_coverage_notes: category_coverage_notes.join("\n"),

    // Used verbatim in synthesis prompts
    synthesis_context: [
      `Corpus: ${relevant_sources} relevant sources of ${total_sources} total`,
      `Period: ${date_range}`,
      `Category breakdown:\n${category_coverage_notes.join("\n")}`,
      thin_categories.length > 0
        ? `⚠ Thin evidence warning: ${thin_categories.join(", ")} — limit confidence to medium or low`
        : "",
    ].filter(Boolean).join("\n"),
  };
}

// ── Evidence graph ────────────────────────────────────────────────────────────
// A lightweight graph of source→evidence→entity→category relationships.
// Used by the dashboard query engine for graph traversal.

/**
 * Build an evidence graph from sources and evidence items.
 *
 * Nodes: { id, type, label, category, date }
 * Edges: { from, to, rel }
 *
 * @param {object[]} sources        - Understood sources
 * @param {object[]} evidenceItems  - From extractAllEvidence()
 * @returns {{ nodes: object[], edges: object[] }}
 */
export function buildEvidenceGraph(sources, evidenceItems) {
  const nodes = [];
  const edges = [];
  const nodeIds = new Set();

  function addNode(node) {
    if (!nodeIds.has(node.id)) {
      nodes.push(node);
      nodeIds.add(node.id);
    }
  }

  // Source nodes
  for (const s of sources) {
    addNode({
      id:       `src:${s.id}`,
      type:     "source",
      label:    s.title?.slice(0, 80) || s.id,
      category: s.category,
      date:     s.date_published,
      trust_tier: s.trust_tier,
      source_type: s.source_type,
    });

    // Source → category
    edges.push({ from: `src:${s.id}`, to: `cat:${s.category}`, rel: "belongs_to" });

    // Source → tags
    for (const tag of s.primary_tags || []) {
      const tagNode = `tag:${tag}`;
      addNode({ id: tagNode, type: "tag", label: tag, category: s.category });
      edges.push({ from: `src:${s.id}`, to: tagNode, rel: "tagged_with" });
    }

    // Source → entities
    for (const entity of s.key_entities || []) {
      if (!entity || typeof entity !== "string") continue;
      const eId = `entity:${entity.toLowerCase().replace(/\s+/g, "_")}`;
      addNode({ id: eId, type: "entity", label: entity });
      edges.push({ from: `src:${s.id}`, to: eId, rel: "mentions" });
    }
  }

  // Evidence nodes
  for (const ei of evidenceItems) {
    if (!ei.is_cluster_rep) continue; // only rep items in graph

    addNode({
      id:           `ev:${ei.evidence_id}`,
      type:         "evidence",
      label:        ei.fact?.slice(0, 100) || ei.evidence_id,
      category:     ei.category,
      evidence_type: ei.evidence_type,
      specificity:  ei.specificity,
      quote_grounded: ei.quote_grounded,
      date:         null, // inherited from source
    });

    // Evidence → source
    edges.push({ from: `ev:${ei.evidence_id}`, to: `src:${ei.source_id}`, rel: "extracted_from" });

    // Evidence → tags
    for (const tag of ei.technique_tags || []) {
      const tagNode = `tag:${tag}`;
      addNode({ id: tagNode, type: "tag", label: tag });
      edges.push({ from: `ev:${ei.evidence_id}`, to: tagNode, rel: "demonstrates" });
    }

    // Evidence → entities
    for (const entity of ei.entities || []) {
      const eId = `entity:${entity.toLowerCase().replace(/\s+/g, "_")}`;
      addNode({ id: eId, type: "entity", label: entity });
      edges.push({ from: `ev:${ei.evidence_id}`, to: eId, rel: "involves" });
    }
  }

  // Category nodes
  for (const cat of ["traditional_ai_threats", "llm_threats", "agentic_ai_threats", "ai_enabled_threats"]) {
    addNode({ id: `cat:${cat}`, type: "category", label: cat });
  }

  return { nodes, edges };
}
